### ISSUE TITLE
Didn't create the json files after I have enabled all singularities

### ISSUE THREAD

**Issue by giobbo98** [CuboidDroid/cuboidresgen#1]
As the title reads, I have enabled all singularities by changing the value from false to true and they appear in game but when I put them in the generators they don't do anything. So I went to check if I left the production enable and, to my surprise, I haven't got any json file in the correct folder but you have said the mod will detect and create a json file for every singularity

EDIT: I did edit my singularities and I tried launching the game with a non edited singularity. Did not work but I guess it could be useful information

**Comment by CuboidDroid** [comment]
If you've got an empty generators folder, could you try deleting that empty folder and then starting the game again to see if the json files generate?

**Comment by nak-attak** [comment]
^^^^^
this does work

**Comment by CuboidDroid** [comment]
Thanks for confirming!
